###  create
POST https://api-node-edzg.onrender.com/videos
Content-Type: application/json

{
    "title": "node",
    "description": "deascrição do video",
    "duration": 180
}
### pesquisa
GET https://api-node-edzg.onrender.com?search=node
### lista de videos
GET https://api-node-edzg.onrender.com
### update
PUT https://api-node-edzg.onrender.com/3c5129b5-2081-4e0b-af78-d1e206200dfb
Content-Type: application/json

{
    "title": "titulo do video",
    "description": "deascrição do video",
    "duration": 180
}
### delete
DELETE https://api-node-edzg.onrender.com/5f205b40-4fea-404a-95f0-ea678f4e7911